const ACTIVE_PICKS = [
  {
    date: '2026-07-05',
    sport: 'WNBA',
    league: 'WNBA',
    category: 'VIP',
    access: 'VIP',
    section: 'vip',
    game: 'Dallas Wings vs Toronto Tempo',
    pick: 'Dallas Wings -5.5',
    betType: 'Spread',
    bet_type: 'Spread',
    pick_type: 'Spread',
    odds: '-110',
    units: '1.00u',
    grade: 'A-',
    confidence: '8.6/10',
    bestNumber: '-5.5',
    best_number: '-5.5',
    line: '-5.5',
    playableTo: '-6.5',
    noBetCutoff: '-7 or worse',
    risk: 'Medium',
    status: 'Active',
    releaseStatus: 'VIP Released',
    sportsbook: 'Circa / shop best spread',
    shortAnalysis: 'Dallas has the cleaner favorite profile at home against Toronto, with the market showing a clear gap between the Wings and Tempo.',
    analysis: 'Dallas is the best VIP add on the July 5 WNBA board. The Wings are laying a manageable number against Toronto, and the matchup lines up with the stronger offense, stronger market profile, and better home-side setup.',
    fullAnalysis: `Dallas Wings -5.5 is the cleanest VIP position on the July 5 slate because it gives us a true favorite profile without forcing an inflated moneyline or a risky parlay. Circa has Dallas priced as a clear favorite, and that matters because the spread is still within a playable range. The Wings do not need a blowout to cash this number; they need a controlled home win with offensive efficiency and enough separation late.\n\nToronto is dangerous enough offensively to avoid reckless exposure, but the defensive profile is the reason this play fits. The Tempo have shown enough leakage on that end that Dallas can get to scoring runs and force Toronto into catch-up basketball. That is exactly the kind of setup where a mid-range favorite can cover without needing everything to go perfectly.\n\nThe reason this is A- instead of full A is spread tax. At -5.5, there is still backdoor exposure if Dallas lets the pace get loose late or if Toronto gets hot from three. But compared to the rest of the slate, this is the best combination of matchup, market support, and playable number.\n\nMicks Verdict: VIP A-, 1.00u. Play -5.5. Still playable to -6.5. Pass at -7 or worse.`,
    writeup: 'Dallas is the best VIP add on the July 5 WNBA board. The Wings are laying a manageable number against Toronto, and the matchup lines up with the stronger offense, stronger market profile, and better home-side setup.',
    sourceVerification: 'Uploaded Circa WNBA July 5 sheet, DocSports Dallas support, Micks Picks WNBA framework',
    birthdayNotes: 'No meaningful July 5 birthday edge. Narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'WNBA',
    league: 'WNBA',
    category: 'VIP',
    access: 'VIP',
    section: 'vip',
    game: 'Indiana Fever vs Las Vegas Aces',
    pick: 'Las Vegas Aces -3',
    betType: 'Spread',
    bet_type: 'Spread',
    pick_type: 'Spread',
    odds: '-110',
    units: '0.75u',
    grade: 'B+',
    confidence: '8.0/10',
    bestNumber: '-3',
    best_number: '-3',
    line: '-3',
    playableTo: '-3.5',
    noBetCutoff: '-4.5 or worse',
    risk: 'Medium-High',
    status: 'Active',
    releaseStatus: 'VIP Released',
    sportsbook: 'Circa / shop best spread',
    shortAnalysis: 'The Aces are playable at the short -3 number, but this is not an A-grade because recent Aces cover risk is real.',
    analysis: 'Aces -3 is the correct side at the better market number, but it should not be treated as a max-unit A play. Las Vegas still has the better top-end roster and more reliable late-game structure, while Indiana has enough offensive talent to keep the game close.',
    fullAnalysis: `Las Vegas -3 is a playable VIP position because the number is meaningfully better than the wider market and gives the Aces a manageable cover target. The Aces still profile as the more complete roster, with better top-end talent, more proven late-game shot creation, and the ability to punish Indiana if the Fever go through scoring droughts.\n\nThat said, this cannot be imported as an A-grade play. The same Aces cover risk that hurt the card yesterday still matters. Las Vegas can win games without fully separating, and Indiana’s offensive ceiling is high enough to stay inside numbers if they shoot well or get a strong whistle. That is why this is downgraded to B+ and kept at 0.75u.\n\nThe key is price discipline. At -3, the play is attractive. At -3.5, it remains playable but slightly thinner. Once the number moves past -4, the edge becomes much less attractive because you are asking Las Vegas to win by multiple possessions against a Fever team that can trade baskets late.\n\nMicks Verdict: VIP B+, 0.75u. Play -3. Playable to -3.5. Pass at -4.5 or worse.`,
    writeup: 'Aces -3 is the correct side at the better market number, but it should not be treated as a max-unit A play. Las Vegas still has the better top-end roster and more reliable late-game structure, while Indiana has enough offensive talent to keep the game close.',
    sourceVerification: 'Uploaded Circa WNBA July 5 sheet, DocSports Aces support, Micks Picks WNBA framework',
    birthdayNotes: 'No meaningful July 5 birthday edge. Narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'MLB',
    league: 'MLB',
    category: 'VIP',
    access: 'VIP',
    section: 'vip',
    game: 'Detroit Tigers vs Texas Rangers',
    pick: 'Detroit Tigers ML',
    betType: 'Moneyline',
    bet_type: 'Moneyline',
    pick_type: 'Moneyline',
    odds: '-114',
    units: '0.75u',
    grade: 'B+',
    confidence: '8.1/10',
    bestNumber: '-114',
    best_number: '-114',
    line: '-114',
    playableTo: '-125',
    noBetCutoff: '-130 or worse',
    risk: 'Medium',
    status: 'Active',
    releaseStatus: 'VIP Released',
    sportsbook: 'Circa / shop best ML',
    shortAnalysis: 'Detroit is worth a VIP add only at the cheaper Circa-style number. The edge disappears if the market gets close to the inflated DocSports price.',
    analysis: 'Tigers ML is playable because the number is still reasonable near -114. DocSports also supports Detroit but at a much higher price, which tells us the side is right but the number matters.',
    fullAnalysis: `Detroit Tigers ML fits the VIP card because it gives us side agreement without forcing a bad price. Circa’s number around -114 is the key. At that range, Detroit is a playable favorite with enough matchup and market support to justify B+ status. DocSports also lands on Detroit, but the higher listed price is not the number we want to chase.\n\nThe Tigers are the stronger side when priced close to pick’em/fair favorite territory. This is not a spot where we need to get cute with the run line or add unnecessary parlay risk. The cleanest expression is the moneyline at the best available price.\n\nThe risk is market inflation. If this gets steamed toward -130 or worse, the value starts disappearing. Micks Picks does not blindly tail consensus after the number is gone. The edge is Detroit at the right price, not Detroit at any price.\n\nMicks Verdict: VIP B+, 0.75u. Play near -114 to -120. Playable to -125. Pass at -130 or worse.`,
    writeup: 'Tigers ML is playable because the number is still reasonable near -114. DocSports also supports Detroit but at a much higher price, which tells us the side is right but the number matters.',
    sourceVerification: 'Uploaded Circa MLB July 5 sheet, DocSports Detroit support, VSiN/Greg fair-price support, Micks Picks MLB framework',
    birthdayNotes: 'No meaningful July 5 birthday edge. Narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'Multi-Sport',
    league: 'WNBA/MLB',
    category: 'VIP Parlay',
    access: 'VIP',
    section: 'vip',
    game: 'Wings / Aces / Tigers',
    pick: 'Dallas Wings ML + Las Vegas Aces ML + Detroit Tigers ML',
    betType: 'Parlay',
    bet_type: 'Parlay',
    pick_type: 'Parlay',
    odds: '+230 estimated',
    units: '0.25u',
    grade: 'B-',
    confidence: '7.4/10',
    bestNumber: '+220 or better',
    best_number: '+220 or better',
    line: '+230 estimated',
    playableTo: '+200',
    noBetCutoff: 'Below +200',
    risk: 'High',
    status: 'Active',
    releaseStatus: 'VIP Released',
    sportsbook: 'Shop best parlay price',
    shortAnalysis: 'Safer VIP parlay version using moneylines instead of laying all spread legs.',
    analysis: 'This is the lower-volatility VIP parlay. It keeps the same core reads from the card — Wings, Aces, and Tigers — but uses moneylines to reduce spread-cover risk.',
    fullAnalysis: `This is the lower-volatility VIP parlay version of the July 5 card. Instead of forcing Dallas -5.5, Las Vegas -3, and Detroit ML together, the safer construction uses Wings ML, Aces ML, and Tigers ML. That lowers the chance of losing a leg on a backdoor cover or a favorite winning without margin.\n\nThe tradeoff is price. You will not get the same payout as the full spread parlay, but the structure is cleaner and more consistent with bankroll discipline after yesterday’s spread variance. This should remain a small-stake add-on, not a replacement for the straight VIP card.\n\nMicks Verdict: VIP Parlay B-, 0.25u. Play only if the combined price is around +220 or better.`,
    writeup: 'Safer VIP parlay version using Wings ML, Aces ML, and Tigers ML instead of laying all spread legs. Small stake only.',
    sourceVerification: 'Built from July 5 VIP card and Circa sheet moneylines',
    birthdayNotes: 'No birthday edge. Narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'Soccer',
    league: 'FIFA World Cup',
    category: 'Free',
    access: 'Free',
    section: 'free',
    game: 'England vs Mexico',
    pick: 'First Half Draw',
    betType: 'First Half Result',
    bet_type: 'First Half Result',
    pick_type: '1H Draw',
    odds: '+100',
    units: '0.35u',
    grade: 'B',
    confidence: '7.3/10',
    bestNumber: '+100',
    best_number: '+100',
    line: '+100',
    playableTo: '-105',
    noBetCutoff: '-110 or worse',
    risk: 'Medium-High',
    status: 'Active',
    releaseStatus: 'Free Released',
    sportsbook: 'Shop best 1H price',
    shortAnalysis: 'Cagey knockout setup points to a slower first half rather than forcing a full-game side.',
    analysis: 'England/Mexico profiles as a cagey knockout match early. Instead of forcing a full-game side, the better angle is the first-half draw.',
    fullAnalysis: 'Free-card play only. The angle is game script: knockout soccer, cautious opening phases, and two sides that are likely to prioritize structure before risk. First-half draw gives us the chance to cash on a slower start without needing to predict the full match winner.',
    writeup: 'England/Mexico profiles as a cagey knockout match early. Instead of forcing a full-game side, the better angle is the first-half draw.',
    sourceVerification: 'VSiN England/Mexico first-half draw support, uploaded World Cup Circa sheet, Micks Picks soccer framework',
    birthdayNotes: 'July 5 soccer birthday notes are narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'MLB',
    league: 'MLB',
    category: 'Free',
    access: 'Free',
    section: 'free',
    game: 'Minnesota Twins vs New York Yankees',
    pick: 'New York Yankees ML',
    betType: 'Moneyline',
    bet_type: 'Moneyline',
    pick_type: 'Moneyline',
    odds: '-131',
    units: '0.50u',
    grade: 'B',
    confidence: '7.2/10',
    bestNumber: '-131',
    best_number: '-131',
    line: '-131',
    playableTo: '-140',
    noBetCutoff: '-145 or worse',
    risk: 'Medium',
    status: 'Active',
    releaseStatus: 'Free Released',
    sportsbook: 'Circa / shop best ML',
    shortAnalysis: 'Prefer the Yankees straight moneyline instead of attaching them to a parlay.',
    analysis: 'Yankees ML is playable as a smaller free-card position. The matchup points to New York as the better side, but the price is not cheap enough for VIP.',
    fullAnalysis: 'Free-card play only. Yankees ML fits because the favorite price is still manageable and avoids parlay variance. Play near -131. Pass if the number gets too inflated.',
    writeup: 'Yankees ML is playable as a smaller free-card position. The matchup points to New York as the better side, but the price is not cheap enough for VIP.',
    sourceVerification: 'Uploaded Circa MLB July 5 sheet, DocSports Yankees support, Micks Picks MLB framework',
    birthdayNotes: 'No meaningful July 5 birthday edge. Narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'MLB',
    league: 'MLB',
    category: 'Free',
    access: 'Free',
    section: 'free',
    game: 'San Diego Padres vs Los Angeles Dodgers',
    pick: 'Los Angeles Dodgers -1.5',
    betType: 'Run Line',
    bet_type: 'Run Line',
    pick_type: 'Run Line',
    odds: 'EVEN',
    units: '0.50u',
    grade: 'B',
    confidence: '7.1/10',
    bestNumber: 'EVEN',
    best_number: 'EVEN',
    line: '-1.5',
    playableTo: '-110',
    noBetCutoff: '-115 or worse',
    risk: 'Medium-High',
    status: 'Active',
    releaseStatus: 'Free Released',
    sportsbook: 'Circa / shop best run line',
    shortAnalysis: 'Dodgers are the right side, but the moneyline is too expensive. The run line is the only playable version.',
    analysis: 'Dodgers -1.5 is the better way to attack the matchup because the moneyline is too expensive. This is not a VIP release because run-line favorites carry variance.',
    fullAnalysis: 'Free-card play only. The Dodgers have the stronger profile, but laying a big moneyline is not worth it. Use the run line at even money or better. Keep the stake controlled because Padres/Dodgers games can stay tight late.',
    writeup: 'Dodgers -1.5 is the better way to attack the matchup because the moneyline is too expensive. This is not a VIP release because run-line favorites carry variance.',
    sourceVerification: 'Uploaded Circa MLB July 5 sheet, DocSports Dodgers support, Micks Picks MLB framework',
    birthdayNotes: 'No meaningful July 5 birthday edge. Narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'MLB',
    league: 'MLB',
    category: 'Props',
    access: 'Free',
    section: 'props',
    game: 'San Diego Padres vs Los Angeles Dodgers',
    pick: 'Fernando Tatis Jr. Home Run Yes',
    betType: 'Player Prop',
    bet_type: 'Player Prop',
    pick_type: 'HR Prop',
    odds: '+340',
    units: '0.10u',
    grade: 'C+',
    confidence: '6.4/10',
    bestNumber: '+340',
    best_number: '+340',
    line: 'HR Yes',
    playableTo: '+320',
    noBetCutoff: '+300 or worse',
    risk: 'Very High',
    status: 'Active',
    releaseStatus: 'Props Lab',
    sportsbook: 'Circa / shop HR price',
    shortAnalysis: 'Power-only HR lotto exposure from the Circa props sheet. Small stake only.',
    analysis: 'This is not a core straight bet. It is a Props Lab HR lottery piece at a playable plus-money price.',
    fullAnalysis: 'Props Lab only. Home run props are high-variance by nature, so this stays at 0.10u. Tatis gives the card a plus-money power shot in the Dodgers/Padres game without tying up the main card.',
    writeup: 'Props Lab only. HR props are high variance, so this stays small at 0.10u.',
    sourceVerification: 'Uploaded Circa MLB Daily Props July 5 sheet',
    birthdayNotes: 'No birthday edge. Narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'MLB',
    league: 'MLB',
    category: 'Props',
    access: 'Free',
    section: 'props',
    game: 'San Diego Padres vs Los Angeles Dodgers',
    pick: 'Shohei Ohtani Home Run Yes',
    betType: 'Player Prop',
    bet_type: 'Player Prop',
    pick_type: 'HR Prop',
    odds: '+425',
    units: '0.10u',
    grade: 'C+',
    confidence: '6.3/10',
    bestNumber: '+425',
    best_number: '+425',
    line: 'HR Yes',
    playableTo: '+400',
    noBetCutoff: '+380 or worse',
    risk: 'Very High',
    status: 'Active',
    releaseStatus: 'Props Lab',
    sportsbook: 'Circa / shop HR price',
    shortAnalysis: 'Plus-money Dodgers power prop. Lotto only, not a core play.',
    analysis: 'Ohtani HR Yes is a high-variance Props Lab piece. Keep it separate from the main Dodgers run-line position.',
    fullAnalysis: 'Props Lab only. Ohtani gives the card a second plus-money HR look in the Dodgers/Padres game, but this is strictly lottery exposure and should remain at 0.10u.',
    writeup: 'Props Lab only. Ohtani HR Yes is high-variance lottery exposure, not a core play.',
    sourceVerification: 'Uploaded Circa MLB Daily Props July 5 sheet',
    birthdayNotes: 'No birthday edge. Narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'MLB',
    league: 'MLB',
    category: 'Props',
    access: 'Free',
    section: 'props',
    game: 'Philadelphia Phillies vs Kansas City Royals',
    pick: 'Aaron Nola Over 4.5 Strikeouts',
    betType: 'Player Prop',
    bet_type: 'Player Prop',
    pick_type: 'Strikeout Prop',
    odds: '-155',
    units: '0.25u',
    grade: 'B-',
    confidence: '6.9/10',
    bestNumber: '-155',
    best_number: '-155',
    line: 'Over 4.5 Ks',
    playableTo: '-160',
    noBetCutoff: '-170 or worse',
    risk: 'Medium-High',
    status: 'Active',
    releaseStatus: 'Props Lab',
    sportsbook: 'Circa / shop K prop',
    shortAnalysis: 'Cleaner prop than the HR lottos, but the juice keeps it small.',
    analysis: 'Nola Over 4.5 strikeouts is the cleaner prop from the board, but the -155 price keeps this to 0.25u.',
    fullAnalysis: 'Props Lab only. Nola’s 4.5 strikeout line is playable, but the juice is heavy enough that this should not be promoted to a main-card play. Keep it at 0.25u and pass if the price worsens.',
    writeup: 'Cleaner prop than the HR lottos, but the juice keeps it small.',
    sourceVerification: 'Uploaded Circa MLB Daily Props July 5 sheet',
    birthdayNotes: 'No birthday edge. Narrative only.'
  },
  {
    date: '2026-07-05',
    sport: 'MLB',
    league: 'MLB',
    category: 'Lotto Parlay',
    access: 'Free',
    section: 'parlays',
    game: 'Yankees / Dodgers / Tigers',
    pick: 'Yankees ML + Dodgers -1.5 + Tigers ML',
    betType: 'Lotto Parlay',
    bet_type: 'Lotto Parlay',
    pick_type: 'Parlay',
    odds: 'TBD',
    units: '0.15u',
    grade: 'C+',
    confidence: '6.6/10',
    bestNumber: 'Best available',
    best_number: 'Best available',
    line: '3-leg parlay',
    playableTo: 'Small stake only',
    noBetCutoff: 'Do not chase bad numbers',
    risk: 'Very High',
    status: 'Active',
    releaseStatus: 'Lotto Released',
    sportsbook: 'Shop best prices',
    shortAnalysis: 'MLB lotto built from the strongest side reads. High variance because Dodgers run line is included.',
    analysis: 'This is a small lotto-only build using Yankees ML, Dodgers -1.5, and Tigers ML. Do not treat this like a straight-card replacement.',
    fullAnalysis: 'Lotto only. The best structure is Yankees ML plus Tigers ML with Dodgers run line for payout. The Dodgers leg creates variance, so this is capped at 0.15u.',
    writeup: 'Small lotto-only build using Yankees ML, Dodgers -1.5, and Tigers ML. High variance; capped at 0.15u.',
    sourceVerification: 'Built from July 5 Micks Picks card and uploaded Circa MLB sheet',
    birthdayNotes: 'No birthday edge. Narrative only.'
  },
  {
    date: '2026-07-06',
    sport: 'Soccer',
    league: 'FIFA World Cup',
    category: 'Monday Hold',
    access: 'Free',
    section: 'watchlist',
    game: 'USA vs Belgium',
    pick: 'Over 2.5 Goals',
    betType: 'Total',
    bet_type: 'Total',
    pick_type: 'Total',
    odds: '-125',
    units: '0.75u',
    grade: 'B+',
    confidence: '8.0/10',
    bestNumber: '-125',
    best_number: '-125',
    line: 'Over 2.5',
    playableTo: '-135',
    noBetCutoff: '-140 or worse',
    risk: 'Medium',
    status: 'Hold',
    releaseStatus: 'Monday Hold',
    sportsbook: 'Shop best total',
    shortAnalysis: 'Best Monday soccer total angle. Do not grade as July 5.',
    analysis: 'USA/Belgium Over 2.5 is a Monday hold, not a July 5 official result. The matchup points to chances at both ends.',
    fullAnalysis: 'Monday hold only. This belongs on the next card if the number stays playable. Over 2.5 is the cleaner angle than picking a winner in a match where both teams are priced evenly to advance.',
    writeup: 'USA/Belgium Over 2.5 is a Monday hold, not a July 5 official result.',
    sourceVerification: 'VSiN USA/Belgium Over support, uploaded World Cup Circa sheet, Micks Picks soccer framework',
    birthdayNotes: 'No meaningful July 5 birthday edge. Narrative only.'
  },
  {
    date: '2026-07-06',
    sport: 'Soccer',
    league: 'FIFA World Cup',
    category: 'Monday Hold',
    access: 'Free',
    section: 'watchlist',
    game: 'Spain vs Portugal',
    pick: 'Spain to Advance',
    betType: 'To Advance',
    bet_type: 'To Advance',
    pick_type: 'To Advance',
    odds: '-210',
    units: '0.75u',
    grade: 'B+',
    confidence: '8.0/10',
    bestNumber: '-210',
    best_number: '-210',
    line: '-210',
    playableTo: '-225',
    noBetCutoff: '-240 or worse',
    risk: 'Medium',
    status: 'Hold',
    releaseStatus: 'Monday Hold',
    sportsbook: 'Circa / shop best advance price',
    shortAnalysis: 'Spain to advance is safer than Spain ML because knockout draw risk matters.',
    analysis: 'Spain to Advance is the preferred Monday version over Spain full-time ML. Spain is the better side, but knockout soccer introduces extra-time and penalty variance.',
    fullAnalysis: 'Monday hold only. Spain is the preferred side, but the safer Micks expression is to advance rather than regulation moneyline. This protects against a 90-minute draw while still backing the better team to survive the tie.',
    writeup: 'Spain to Advance is the preferred Monday version over Spain full-time ML.',
    sourceVerification: 'Uploaded World Cup Circa sheet, market preview support, Micks Picks soccer framework',
    birthdayNotes: 'July 5 soccer birthday notes are narrative only.'
  },
  {
    date: '2026-07-06',
    sport: 'Soccer',
    league: 'FIFA World Cup',
    category: 'Monday Parlay Hold',
    access: 'Free',
    section: 'parlays',
    game: 'Spain / USA-Belgium',
    pick: 'Spain to Advance + USA/Belgium Over 2.5 Goals',
    betType: 'Parlay',
    bet_type: 'Parlay',
    pick_type: 'Parlay',
    odds: 'TBD',
    units: '0.25u',
    grade: 'B-',
    confidence: '7.2/10',
    bestNumber: 'Best available',
    best_number: 'Best available',
    line: '2-leg parlay',
    playableTo: 'Small stake only',
    noBetCutoff: 'Do not chase if Spain to advance exceeds -240 or total exceeds -140',
    risk: 'High',
    status: 'Hold',
    releaseStatus: 'Monday Hold',
    sportsbook: 'Shop best prices',
    shortAnalysis: 'Monday soccer parlay hold using the safer Spain market and the strongest USA/Belgium total angle.',
    analysis: 'Hold for Monday only. Spain to advance protects against knockout draw risk, while USA/Belgium Over 2.5 is the stronger game-script total.',
    fullAnalysis: 'Monday parlay hold only. This should not be graded on July 5. It combines the safer Spain to advance position with the USA/Belgium Over 2.5 angle. Keep this smaller than the straight plays.',
    writeup: 'Monday soccer parlay hold using Spain to advance and USA/Belgium Over 2.5.',
    sourceVerification: 'Built from Monday World Cup holds and uploaded Circa sheet',
    birthdayNotes: 'No birthday edge. Narrative only.'
  }
]

const WEEKLY_RESULTS = []
const emptyStats = { wins: 0, losses: 0, pushes: 0, record: '0-0', units: '+0.00u', netUnits: 0, winRate: '0%' }

function hasSettlement(row = {}) {
  const marker = [row.Result, row.result, row.Outcome, row.outcome, row.Status, row.status].join(' ')
  return /win|loss|push|void|settled|graded/i.test(marker)
}

function activeRows(rows = []) {
  return rows.filter(row => row && (row.pick || row.Pick) && !hasSettlement(row))
}

function includesAny(row = {}, patterns = []) {
  const blob = [row.category, row.section, row.betType, row.bet_type, row.pick_type, row.releaseStatus].join(' ')
  return patterns.some(pattern => new RegExp(pattern, 'i').test(blob))
}

export default async function handler(req, res) {
  const active = activeRows(ACTIVE_PICKS)
  const vip = active.filter(row => String(row.access || row.Access || '').toLowerCase() === 'vip')
  const free = active.filter(row => String(row.access || row.Access || '').toLowerCase() === 'free' && !includesAny(row, ['prop', 'parlay', 'hold']))
  const props = active.filter(row => includesAny(row, ['prop']))
  const parlays = active.filter(row => includesAny(row, ['parlay', 'lotto']))
  const holds = active.filter(row => /hold|watchlist/i.test(String(row.status || row.releaseStatus || row.section || '')))

  res.status(200)
  res.setHeader('Content-Type', 'application/json')
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0')
  res.end(JSON.stringify({
    ok: true,
    success: true,
    source: 'vip-vault-july-5-active-card-props-parlays',
    sourceOfTruth: 'Micks Picks VIP Vault',
    date: '2026-07-05',
    activePicks: active,
    vip,
    vipVault: vip,
    free,
    props,
    parlay: parlays,
    parlays,
    lotto: parlays,
    lottoParlays: parlays,
    watchlist: holds,
    mondayHolds: holds,
    rows: active,
    records: active,
    picks: active,
    weeklyResults: WEEKLY_RESULTS,
    results: WEEKLY_RESULTS,
    resultRows: WEEKLY_RESULTS,
    archive: WEEKLY_RESULTS,
    resultsArchive: WEEKLY_RESULTS,
    record: emptyStats.record,
    overallRecord: emptyStats.record,
    units: emptyStats.units,
    totalUnits: emptyStats.units,
    winRate: emptyStats.winRate,
    sectionRecords: emptyStats,
    metrics: emptyStats,
    stats: emptyStats
  }))
}
