const vipRows = [
  {
    date: '2026-07-06', sport: 'Soccer', league: 'FIFA World Cup', access: 'VIP', category: 'VIP', section: 'vip',
    game: 'Spain vs Portugal', pick: 'Spain to Advance', cardTitle: 'Spain to Advance', betType: 'To Advance', odds: '-210', units: '1.00u', grade: 'A-', confidence: '8.6/10', bestNumber: '-210', lineNumber: '-210', noBetCutoff: '-240 or worse', status: 'Active', releaseStatus: 'VIP Released', sportsbook: 'Circa / shop best advance price',
    shortAnalysis: 'Spain is the preferred side, but the advance market is safer than Spain 90-minute ML because knockout draw risk matters.',
    writeup: 'Spain to Advance is the cleanest VIP expression on the World Cup board. Spain profiles as the better side, but this is knockout soccer, so forcing a 90-minute moneyline creates unnecessary draw risk. The advance market protects the position through extra time and penalties while still backing the better team to survive the tie.',
    analysis: 'Spain to Advance is the preferred VIP structure over Spain 90-minute ML because the matchup supports Spain as the stronger side without requiring them to win inside regulation. Circa shows Spain as the regulation favorite and also prices Spain to advance as the clear but not overwhelming favorite. That matters because the draw probability is meaningful in a Portugal-Spain knockout matchup. The goal is not to overpay for narrative or force a side at a fragile number. Spain to Advance protects against a 90-minute draw while still capturing the core handicap: Spain has the better tournament profile and should be trusted more to survive the tie. Micks Verdict: VIP A-, 1.00u. Play around -210. Playable to -225. Pass if it gets worse than -240.',
    fullAnalysis: 'Spain to Advance is the preferred VIP structure over Spain 90-minute ML because the matchup supports Spain as the stronger side without requiring them to win inside regulation. Circa shows Spain as the regulation favorite and also prices Spain to advance as the clear but not overwhelming favorite. That matters because the draw probability is meaningful in a Portugal-Spain knockout matchup.\n\nThe goal is not to overpay for narrative or force a side at a fragile number. Spain to Advance protects against a 90-minute draw while still capturing the core handicap: Spain has the better tournament profile and should be trusted more to survive the tie.\n\nThis is exactly why the advance market is the Micks Picks version. If Spain wins in regulation, the ticket cashes. If the match becomes cagey and reaches extra time or penalties, the position is still alive instead of dying on the 90-minute draw. That protection matters in a knockout setting with two high-end teams.\n\nMicks Verdict: VIP A-, 1.00u. Play around -210. Playable to -225. Pass if it gets worse than -240.',
    birthdayNotes: 'July 6 football birthdays, for example Zé Roberto and Rory Delap, are narrative only and should not be treated as edge.'
  },
  {
    date: '2026-07-06', sport: 'Soccer', league: 'FIFA World Cup', access: 'VIP', category: 'VIP', section: 'vip',
    game: 'USA vs Belgium', pick: 'Over 2.5 Goals', cardTitle: 'USA/Belgium Over 2.5 Goals', betType: 'Total', odds: '-125', units: '0.75u', grade: 'B+', confidence: '8.1/10', bestNumber: '-125', lineNumber: 'Over 2.5', noBetCutoff: '-140 or worse', status: 'Active', releaseStatus: 'VIP Released', sportsbook: 'Circa / shop best total',
    shortAnalysis: 'The better angle is goals instead of a side. Both attacks have enough chance creation to push this over.',
    writeup: 'USA vs Belgium profiles as an open knockout match with attacking talent on both sides. Instead of forcing a winner in a match where both teams are close to pick em to advance, the cleaner play is Over 2.5 goals.',
    analysis: 'USA/Belgium Over 2.5 remains the best total angle on the July 6 World Cup board. Both sides have enough attacking quality to create chances, and the market does not give either team a dominant side edge. That makes the total more attractive than trying to pick the winner. The key handicap is game state. If either team scores first, the match can open quickly because the trailing side has enough attacking pieces to respond. Belgium has elite chance creation profiles, while the USA has enough pace and front-line threat to make this more of a transition game than a cagey 1-0 profile. Micks Verdict: VIP B+, 0.75u. Play Over 2.5 around -125. Playable to -135. Pass at -140 or worse.',
    fullAnalysis: 'USA/Belgium Over 2.5 remains the best total angle on the July 6 World Cup board. Both sides have enough attacking quality to create chances, and the market does not give either team a dominant side edge. That makes the total more attractive than trying to pick the winner.\n\nThe key handicap is game state. If either team scores first, the match can open quickly because the trailing side has enough attacking pieces to respond. Belgium has high-end chance creation and individual attacking quality, while the USA has enough pace and front-line threat to create transition chances and force Belgium into defending space.\n\nThis is not a spot where Micks Picks needs to force USA or Belgium as the side. The better angle is that the matchup can produce enough quality looks for three goals, especially if the first goal arrives before the match settles into a late knockout-game shell.\n\nMicks Verdict: VIP B+, 0.75u. Play Over 2.5 around -125. Playable to -135. Pass at -140 or worse.',
    birthdayNotes: 'July 6 football birthdays, for example Zé Roberto and Rory Delap, are narrative only and should not be treated as edge.'
  }
]

const freeRows = [
  { date: '2026-07-06', sport: 'WNBA', league: 'WNBA', access: 'Free', category: 'Free', section: 'free', game: 'Connecticut Sun vs Minnesota Lynx', pick: 'Minnesota Lynx -13', cardTitle: 'Minnesota Lynx -13', betType: 'Spread', odds: '-110', units: '0.75u', grade: 'B+', confidence: '7.9/10', bestNumber: '-13', lineNumber: '-13', noBetCutoff: '-14.5 or worse', status: 'Active', releaseStatus: 'Free Released', sportsbook: 'Circa', writeup: 'Minnesota is clearly superior, but the spread size keeps this out of VIP.' },
  { date: '2026-07-06', sport: 'WNBA', league: 'WNBA', access: 'Free', category: 'Free', section: 'free', game: 'Golden State Valkyries vs Washington Mystics', pick: 'Golden State Valkyries -6', cardTitle: 'Golden State Valkyries -6', betType: 'Spread', odds: '-110', units: '0.50u', grade: 'B', confidence: '7.2/10', bestNumber: '-6', lineNumber: '-6', noBetCutoff: '-6.5 or worse', status: 'Active', releaseStatus: 'Free Released', sportsbook: 'Circa', writeup: 'Golden State is playable small only at -6.' },
  { date: '2026-07-06', sport: 'WNBA', league: 'WNBA', access: 'Free', category: 'Free', section: 'free', game: 'Seattle Storm vs Los Angeles Sparks', pick: 'Los Angeles Sparks -4', cardTitle: 'Los Angeles Sparks -4', betType: 'Spread', odds: '-110', units: '0.50u', grade: 'B', confidence: '7.1/10', bestNumber: '-4', lineNumber: '-4', noBetCutoff: '-4.5 or worse', status: 'Active', releaseStatus: 'Free Released', sportsbook: 'Circa', writeup: 'Sparks have the home and offensive edge.' },
  { date: '2026-07-06', sport: 'MLB', league: 'MLB', access: 'Free', category: 'Free', section: 'free', game: 'Colorado Rockies vs Los Angeles Dodgers', pick: 'Los Angeles Dodgers -1.5', cardTitle: 'Los Angeles Dodgers -1.5', betType: 'Run Line', odds: '-118', units: '0.50u', grade: 'B', confidence: '7.4/10', bestNumber: '-118', lineNumber: '-1.5', noBetCutoff: '-130 or worse', status: 'Active', releaseStatus: 'Free Released', sportsbook: 'Circa', writeup: 'Dodgers moneyline is too expensive, so the run line is the better angle.' },
  { date: '2026-07-06', sport: 'MLB', league: 'MLB', access: 'Free', category: 'Free', section: 'free', game: 'New York Mets vs Atlanta Braves', pick: 'Atlanta Braves ML', cardTitle: 'Atlanta Braves ML', betType: 'Moneyline', odds: '-126', units: '0.50u', grade: 'B', confidence: '7.5/10', bestNumber: '-126', lineNumber: '-126', noBetCutoff: '-145 or worse', status: 'Active', releaseStatus: 'Free Released', sportsbook: 'Circa', writeup: 'Braves are playable at the reasonable favorite price.' },
  { date: '2026-07-06', sport: 'MLB', league: 'MLB', access: 'Free', category: 'Free', section: 'free', game: 'Arizona Diamondbacks vs San Diego Padres', pick: 'Arizona Diamondbacks +1.5', cardTitle: 'Arizona Diamondbacks +1.5', betType: 'Run Line', odds: '-195', units: '0.50u', grade: 'B', confidence: '7.0/10', bestNumber: '-195', lineNumber: '+1.5', noBetCutoff: '-210 or worse', status: 'Active', releaseStatus: 'Free Released', sportsbook: 'Circa', writeup: 'Arizona +1.5 is the safer way to play a competitive game.' }
]

const propRows = [
  { date: '2026-07-06', sport: 'MLB', league: 'MLB', access: 'Free', category: 'Props', section: 'props', game: 'Props Lab', pick: 'No Official Props Released', cardTitle: 'No Official Props Released', betType: 'Props Notice', odds: 'N/A', units: '0.00u', grade: 'Pass', confidence: 'Pass', bestNumber: 'Need exact player and price', lineNumber: 'Props held', noBetCutoff: 'Do not play without exact number', status: 'Hold', releaseStatus: 'Props Held', sportsbook: 'TBD', writeup: 'Props are not official until exact player, market, odds, and sportsbook are confirmed.' }
]

const lottoRows = [
  { date: '2026-07-06', sport: 'Soccer', league: 'FIFA World Cup', access: 'Free', category: 'Lotto Parlay', section: 'lotto', game: 'Spain / USA-Belgium', pick: 'Spain to Advance + USA/Belgium Over 2.5 Goals', cardTitle: 'Spain to Advance + USA/Belgium Over 2.5', betType: 'Lotto Parlay', odds: 'TBD', units: '0.25u', grade: 'B-', confidence: '7.3/10', bestNumber: 'Best available', lineNumber: '2-leg parlay', noBetCutoff: 'Do not chase bad numbers', status: 'Active', releaseStatus: 'Lotto Released', sportsbook: 'Shop best prices', writeup: 'Best soccer parlay build.' },
  { date: '2026-07-06', sport: 'Multi-Sport', league: 'MLB/FIFA World Cup', access: 'Free', category: 'Lotto Parlay', section: 'lotto', game: 'Dodgers / Braves / Spain', pick: 'Dodgers -1.5 + Braves ML + Spain to Advance', cardTitle: 'Dodgers -1.5 + Braves ML + Spain to Advance', betType: 'Lotto Parlay', odds: 'TBD', units: '0.15u', grade: 'C+', confidence: '6.8/10', bestNumber: 'Best available', lineNumber: '3-leg parlay', noBetCutoff: 'Do not chase bad numbers', status: 'Active', releaseStatus: 'Lotto Released', sportsbook: 'Shop best prices', writeup: 'Small mixed-card lotto.' },
  { date: '2026-07-06', sport: 'Multi-Sport', league: 'WNBA/MLB/FIFA World Cup', access: 'Free', category: 'Lotto Parlay', section: 'lotto', game: 'Lynx / Braves / Spain', pick: 'Minnesota Lynx ML + Braves ML + Spain to Advance', cardTitle: 'Lynx ML + Braves ML + Spain to Advance', betType: 'Lotto Parlay', odds: 'TBD', units: '0.20u', grade: 'C+', confidence: '6.9/10', bestNumber: 'Best available', lineNumber: '3-leg safer ML parlay', noBetCutoff: 'Do not chase bad pricing', status: 'Active', releaseStatus: 'Lotto Released', sportsbook: 'Shop best prices', writeup: 'Safer lotto build using Lynx ML instead of spread.' }
]

const mainRows = [...vipRows, ...freeRows]
const allRows = [...mainRows, ...propRows, ...lottoRows]

export default async function handler(req, res) {
  res.setHeader('Content-Type', 'application/json')
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0')
  res.status(200).json({ ok: true, success: true, source: 'vip-vault-july-6-active-card-full-analysis', date: '2026-07-06', activePicks: mainRows, rows: mainRows, records: mainRows, picks: mainRows, mainPicks: mainRows, vip: vipRows, vipPicks: vipRows, vipVault: vipRows, free: freeRows, freePicks: freeRows, props: propRows, propsLab: propRows, propRows, playerProps: propRows, parlay: lottoRows, parlays: lottoRows, lotto: lottoRows, lottoParlays: lottoRows, parlayRows: lottoRows, allRows, record: '0-0', units: '+0.00u' })
}
