const date = '2026-07-08'

const vip = [
  {
    date, sport: 'WNBA', league: 'WNBA', section: 'vip', category: 'VIP', access: 'VIP',
    game: 'Indiana Fever vs Los Angeles Sparks', pick: 'Indiana Fever -6.5', cardTitle: 'Fever -6.5 vs Sparks', betType: 'Spread', odds: '-110', grade: 'B+', units: '0.75u', bestNumber: '-6.5', noBetCutoff: '-7.5 or worse', confidence: '8.0/10', status: 'Active', releaseStatus: 'VIP Released', sportsbook: 'Shop best available', featured: 'Yes', officialBet: 'Yes', pickOfTheDayEligible: 'Yes',
    shortAnalysis: 'Indiana is the preferred side, but VSiN kept this from being an A-grade because projection support was not strong enough.',
    writeup: 'Fever -6.5 stays on the VIP card because Indiana has the cleaner offensive ceiling, stronger guard creation, and a better path to separation against a vulnerable Sparks team.',
    analysis: 'Indiana remains the preferred side against Los Angeles, but the VSiN scan moved this from A- to B+. The matchup still favors the Fever because they have the clearer offensive ceiling and more reliable late-game structure, but laying a mid-range WNBA spread requires number discipline.',
    fullAnalysis: 'Indiana is still the preferred side, but this is no longer an A-grade position after the VSiN scan. The original handicap liked Fever -6.5 because Indiana has the clearer offensive ceiling, the better shot creation profile, and a more trustworthy late-game structure than Los Angeles. The Sparks continue to profile as a vulnerable opponent, especially if their rotation is still short and their offense has to manufacture too much through unstable half-court possessions.\n\nThe reason this stays in the VIP section is matchup quality. Indiana has the better top-end guard play, better pace control, and a stronger path to separation if the game turns into a scoring contest. The Fever do not need a perfect defensive game to cover this number; they need their offense to stay efficient and avoid the type of empty possessions that let an underdog hang around.\n\nThe downgrade from A- to B+ is about number discipline. Laying -6.5 in the WNBA is not the same as laying a short favorite. If the game lands in a late foul-game window, the spread can get uncomfortable. VSiN did not fully confirm this as a model-backed favorite, so Micks Picks should treat it as strong but not elite.\n\nMicks Verdict: Fever -6.5 is a VIP B+ play for 0.75u. Playable at -6.5. Still acceptable at -7. Pass if the market pushes to -7.5 or worse unless injury news strongly favors Indiana.'
  },
  {
    date, sport: 'MLB', league: 'MLB', section: 'vip', category: 'VIP', access: 'VIP',
    game: 'Milwaukee Brewers vs St. Louis Cardinals', pick: 'Milwaukee Brewers ML', cardTitle: 'Brewers ML vs Cardinals', betType: 'Moneyline', odds: '-126', grade: 'B+', units: '0.75u', bestNumber: '-126', noBetCutoff: '-150 or worse', confidence: '8.0/10', status: 'Active', releaseStatus: 'VIP Released', sportsbook: 'Shop best available', featured: 'Yes', officialBet: 'Yes', pickOfTheDayEligible: 'Yes',
    shortAnalysis: 'Brewers ML is the cleanest VSiN-supported add, with enough projection and market support to avoid forcing a run line.',
    writeup: 'Milwaukee fits the VIP profile better than most of the MLB board: manageable moneyline price, market support, and a cleaner win-path than forcing a volatile run line.',
    analysis: 'Brewers ML is the strongest VSiN-backed addition to the July 8 card. The price still leaves room if Milwaukee is closer to a high -140s true number, making the moneyline the cleaner structure than a run-line play.',
    fullAnalysis: 'Brewers ML is the cleanest VSiN-supported add to the card. Milwaukee fits the profile Micks Picks wants from a VIP baseball side: manageable moneyline price, positive market support, and enough projection edge to justify avoiding run-line volatility. Instead of forcing a -1.5 position, the better structure is simply asking Milwaukee to win the game.\n\nThe handicap starts with price. A Brewers moneyline around the mid -120s still leaves enough room if the true number is closer to the high -140s. That gives the bet a cleaner edge than a public-heavy favorite with no value left in the line. Milwaukee also has the more trustworthy complete-game profile, especially if the bullpen path is cleaner than St. Louis late.\n\nThis is not an A-grade because MLB moneylines always carry variance, and a divisional-style matchup can get messy quickly. But compared with the rest of the board, this is one of the more stable positions. It has enough market confirmation and enough projection support to make the VIP card without forcing a bigger stake.\n\nMicks Verdict: Brewers ML is a VIP B+ play for 0.75u. Best around -126. Playable to -145. Pass if the market gets worse than -150.'
  }
]

const free = [
  { date, sport: 'MLB', league: 'MLB', section: 'free', category: 'Free', access: 'Free', game: 'Boston Red Sox vs Chicago White Sox', pick: 'Boston Red Sox ML', cardTitle: 'Red Sox ML vs White Sox', betType: 'Moneyline', odds: '-105', grade: 'B+', units: '0.75u', status: 'Active', releaseStatus: 'Free Released', writeup: 'Boston gets added after VSiN support and market movement pushed the Red Sox from dog range into favorite range. Playable near -105 to -120; pass at -125 or worse.' },
  { date, sport: 'MLB', league: 'MLB', section: 'free', category: 'Free', access: 'Free', game: 'Houston Astros vs Washington Nationals', pick: 'Over 9', cardTitle: 'Astros/Nationals Over 9', betType: 'Total', odds: '-110', grade: 'B', units: '0.50u', status: 'Active', releaseStatus: 'Free Released', writeup: 'The VSiN scan moved this from Astros +1.5 to the game total. Over 9 is the cleaner angle. Pass at 10 or higher.' },
  { date, sport: 'MLB', league: 'MLB', section: 'free', category: 'Free', access: 'Free', game: 'Colorado Rockies vs Los Angeles Dodgers', pick: 'Los Angeles Dodgers -1.5', cardTitle: 'Dodgers -1.5 vs Rockies', betType: 'Run Line', odds: '-126', grade: 'B', units: '0.50u', status: 'Active', releaseStatus: 'Free Released', writeup: 'Dodgers still have the talent gap, but run-line volatility keeps this as a smaller B-grade free-card position.' }
]

const props = [
  { date, sport: 'MLB', league: 'MLB', section: 'props', category: 'Props', access: 'Free', game: 'Houston Astros vs Washington Nationals', player: 'CJ Abrams', prop: 'Over 1.5 Hits + Runs + RBIs', pick: 'CJ Abrams Over 1.5 HRR', cardTitle: 'CJ Abrams O1.5 HRR', betType: 'Player Prop', odds: '-125', grade: 'B', units: '0.50u', status: 'Active', releaseStatus: 'Props Released', writeup: 'Abrams can clear this with a hit, run, RBI, or combined table-setting production.' },
  { date, sport: 'MLB', league: 'MLB', section: 'props', category: 'Props', access: 'Free', game: 'Boston Red Sox vs Chicago White Sox', player: 'Jake Bennett', prop: 'Over 4.5 Strikeouts', pick: 'Jake Bennett Over 4.5 Ks', cardTitle: 'Jake Bennett O4.5 Ks', betType: 'Player Prop', odds: '+110', grade: 'B', units: '0.50u', status: 'Active', releaseStatus: 'Props Released', writeup: 'Bennett Over 4.5 Ks is a plus-money prop with a reasonable strikeout path.' }
]

const lottoParlays = [
  { date, sport: 'MLB', league: 'MLB', section: 'longshots', category: 'Longshots', access: 'Free', game: 'Brewers/Cardinals + Red Sox/White Sox', pick: 'Brewers ML + Red Sox ML', cardTitle: 'Brewers ML + Red Sox ML', legs: 'Milwaukee Brewers ML / Boston Red Sox ML', betType: 'Lotto Parlay', odds: 'TBD', grade: 'B-', units: '0.25u', status: 'Active', releaseStatus: 'Lotto Released', writeup: 'Small two-leg MLB parlay using the two cleanest VSiN-supported moneyline positions.' },
  { date, sport: 'Multi-Sport', league: 'WNBA/MLB', section: 'longshots', category: 'Longshots', access: 'Free', game: 'Fever/Sparks + Brewers/Cardinals + Red Sox/White Sox', pick: 'Fever -6.5 + Brewers ML + Red Sox ML', cardTitle: 'Fever -6.5 + Brewers ML + Red Sox ML', legs: 'Indiana Fever -6.5 / Milwaukee Brewers ML / Boston Red Sox ML', betType: 'Lotto Parlay', odds: 'TBD', grade: 'C+', units: '0.15u', status: 'Active', releaseStatus: 'Lotto Released', writeup: 'Three-leg cross-sport lotto using the top WNBA side and two supported MLB moneylines.' },
  { date, sport: 'MLB', league: 'MLB', section: 'longshots', category: 'Longshots', access: 'Free', game: 'Dodgers/Rockies + Astros/Nationals', pick: 'Dodgers -1.5 + Astros/Nationals Over 9', cardTitle: 'Dodgers -1.5 + Astros/Nationals Over 9', legs: 'Dodgers -1.5 / Astros-Nationals Over 9', betType: 'Lotto Parlay', odds: 'TBD', grade: 'C', units: '0.10u', status: 'Active', releaseStatus: 'Lotto Released', writeup: 'Tiny MLB lotto pairing the Dodgers run-line angle with the Astros/Nats scoring angle.' },
  { date, sport: 'MLB', league: 'MLB Props', section: 'longshots', category: 'Longshots', access: 'Free', game: 'Props Lotto', pick: 'CJ Abrams O1.5 HRR + Jake Bennett O4.5 Ks', cardTitle: 'CJ Abrams O1.5 HRR + Jake Bennett O4.5 Ks', legs: 'CJ Abrams Over 1.5 HRR / Jake Bennett Over 4.5 Ks', betType: 'Props Lotto', odds: 'TBD', grade: 'C', units: '0.10u', status: 'Active', releaseStatus: 'Lotto Released', writeup: 'Optional props lotto only. Keep it tiny or skip.' }
]

const longshots = lottoParlays
const allRows = [...vip, ...free, ...props, ...lottoParlays]

export default function handler(req, res) {
  res.setHeader('Content-Type', 'application/json')
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0')
  res.status(200).json({ success: true, ok: true, source: 'vip-july-8-card-restore-full-analysis', date, vip, vipPicks: vip, vipVault: vip, free, props, propsLab: props, lottoParlays, lotto: lottoParlays, parlays: lottoParlays, longshots, rows: allRows, records: allRows, picks: allRows, activePicks: allRows, allRows })
}
